{% set version = "0.13.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ffbase
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ffbase_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ffbase/ffbase_{{ version }}.tar.gz
  sha256: b3f61f80ba6851130247779786903d42a24ee5219aa24556c8470aece8a2e6b6

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bit
    - r-fastmatch
    - r-ff >=4.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bit
    - r-fastmatch
    - r-ff >=4.0

test:
  commands:
    - $R -e "library('ffbase')"           # [not win]
    - "\"%R%\" -e \"library('ffbase')\""  # [win]

about:
  home: http://github.com/edwindj/ffbase
  license: GPL-3.0-only
  summary: Extends the out of memory vectors of 'ff' with statistical functions and other utilities to ease their usage.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ffbase
# Maintainer: Edwin de Jonge <edwindjonge@gmail.com>
# License: GPL-3
# Title: Basic Statistical Functions for Package 'ff'
# Type: Package
# LazyLoad: yes
# Author: Edwin de Jonge, Jan Wijffels, Jan van der Laan
# Description: Extends the out of memory vectors of 'ff' with statistical functions and other utilities to ease their usage.
# Version: 0.12.7
# URL: http://github.com/edwindj/ffbase
# Depends: R (>= 2.12.0),ff(>= 2.2-11)
# Imports: fastmatch, bit
# Suggests: testthat, parallel, LaF, biglm
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-11-06 23:12:14 UTC; edwin
# Repository: CRAN
# Date/Publication: 2018-11-06 23:40:03 UTC
