appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TuRQE0E4T0K1iu3Iw1mEZkdVKwMfpN7aB4sgDGHzJJJqCbMIw5fZeV2BFEDZTWKWsPdSe3WxCaW5hWiqfTIOUNzyzArITjOnXLTVKhGf+5VHRcyO9MhzqgMESB4iYe5a2MBRKU3rtdz+pjwVa0GySBQ5teozd1FW90L6JsWLDjTX0y43muiiWwIpF+acEHwdpR0AznMLPQp0tYITlzt8vWh6TCq0Xybzyn2OhD1UvzC9DK38tLy2GRH+1NCkVXGZsdka1aLHeUr2ofzKf05KnO0iP+5Emmbry19xzv6Iu2LbRE3oSA+Q5Fl1YEz0AxIF8LLzdvun38d0nXe0BnsYIRaRJwZsQQ04SyEP9MeurDJ9HjYG93AK6pLoXv/MSAJ11+Jdk9zbGs4QYmoUWAyo44SA9LmGD//OEe/C86OJ98lW23qM4ZfhbB5ukOEJLPahE4hAWtmZ0DXHhYnN8H5Gk4JVqQiONUI7Oe89YwTge1gnuUwFfHeepbdU9/TGquP8xwuciNZNoWOU6OtTu9XVBTt2eRQisOCi7o1iP65kmGtaOe8KX0vnSrIYo+dSHzGeVQS71Pp7KsX6TXBWwAlwgE3/VyW1ccU8PsnS9YwPo3gqZqfNpRj4jtkbx9HkMYp/31UpoIkpLHe3zhNHx4FXc7Nv6XZr8LR36k/1fRsNxkw=}
